# fly.toml app configuration file generated for lightmatter-vite-black-tree-1935 on 2023-11-18T22:30:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightmatter-vite-black-tree-1935"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
